<?php

/**
 * @file
 * Contains custom code.
 */

/**
 * Implements hook_plugins_filter_alter().
 */
function views_custom_regex_views_plugins_filter_alter(array &$plugins) {

  // Handles string type fields and
  // performs filtering based on selected commands.
  $plugins['string']['class'] = 'Drupal\views_custom_regex\Plugin\views\filter\RegularExpressionStringFilter';
  // Handles Numeric type fields and
  // performs filtering based on selected commands.
  $plugins['numeric']['class'] = 'Drupal\views_custom_regex\Plugin\views\filter\RegularExpressionNumericFilter';
  // Handles filtering on multiple fields.
  $plugins['combine']['class'] = 'Drupal\views_custom_regex\Plugin\views\filter\RegularExpressionCombinedFilter';
}
