<?php

/**
 * @file
 * Contains views_custom_regex.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_migrate module.
    case 'help.page.views_custom_regex':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows to add Custom Regular expression in views for filters.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_plugins_filter_alter().
 */
function views_custom_regex_views_plugins_filter_alter(array &$plugins) {
  // Overriding class of string filter handler from StringFilter
  // to RegularExpressionStringFilter.
  $plugins['string']['class'] = 'Drupal\views_custom_regex\Plugin\views\filter\RegularExpressionStringFilter';
  // Overriding class of numeric filter handler from NumericFilter
  // to RegularExpressionNumericFilter.
  $plugins['numeric']['class'] = 'Drupal\views_custom_regex\Plugin\views\filter\RegularExpressionNumericFilter';
  // Overriding class of combine filter handler from Combine
  // to RegularExpressionCombinedFilter.
  $plugins['combine']['class'] = 'Drupal\views_custom_regex\Plugin\views\filter\RegularExpressionCombinedFilter';
}
