<?php

/**
 * @file
 * Contains custom code.
 */

/**
 * Implements hook_plugins_filter_alter().
 */
function views_custom_regex_views_plugins_filter_alter(array &$plugins) {
  // Overriding class of string filter handler from StringFilter
  // to RegularExpressionStringFilter.
  $plugins['string']['class'] = 'Drupal\views_custom_regex\Plugin\views\filter\RegularExpressionStringFilter';
  // Overriding class of numeric filter handler from NumericFilter
  // to RegularExpressionNumericFilter.
  $plugins['numeric']['class'] = 'Drupal\views_custom_regex\Plugin\views\filter\RegularExpressionNumericFilter';
  // Overriding class of combine filter handler from Combine
  // to RegularExpressionCombinedFilter.
  $plugins['combine']['class'] = 'Drupal\views_custom_regex\Plugin\views\filter\RegularExpressionCombinedFilter';
}
